### ISSUE TITLE
Inability to subscribe to analog values object due to the "optional-functionality-not-supported" 

### ISSUE THREAD

**Issue by aphilgr1** [Bepacom-Raalte/bepacom-HA-Addons#48]
I am using your integration to control 4 bacnet devices. Devices 77000 and 77001 are heat pumps with Carel controllers. Device 17800 is a loytec controller that runs our BMS and device 77003, is Philips - Dynalite PDDEG with bacnet support. 

On the Philips device, temperature readings work well, but commands for presets and set points, can pass from HA to dynet (Dynalte protocol) but not the other way around. It seems there is only one-way communication, since values changed from dynet, are shown in YABE, but do not pass-htrough to HA. The log file, indicates inability to subscribe to analog values for device 77003 due to the "optional-functionality-not-supported" object.

This is how the Philips device appears in YABE

![image](https://github.com/Bepacom-Raalte/bepacom-HA-Addons/assets/60076375/b712caac-8ac0-4130-961d-247049edfe84)

These are the properties of the data-poins with analogue values that cannot pass from dynet to bacnet

![image](https://github.com/Bepacom-Raalte/bepacom-HA-Addons/assets/60076375/47b74b3b-0078-47c7-8d6d-9ac8a0ecc50f)

this is my log file, downloaded from the integration WebUI

[bacnet_addon_logs (4).txt](https://github.com/Bepacom-Raalte/bepacom-HA-Addons/files/14824973/bacnet_addon_logs.4.txt)

Thanks in advance and congratulations on the integration. I love it!

**Comment by Bepacom-Raalte** [comment]
Hey,

Thank you for using our add-on and integration!
The "optional-functionality-not-supported" message means that this BACnet device does not support Change of Value subscriptions.
Seems there are some more issues with subscribing to certain objects.
The reason Home Assistant isn't getting updated quickly is because the subscription for that object likely failed. This means that the add-on isn't getting notified if it's value changes.

If you're feeling bold, you can try the dev version v1.4.1b4.
In this version, I'm experimenting with configurations for specific devices. 
An example below: 

```yaml
devices_setup:
  - deviceID: device:77003
    CoV_lifetime: 600 #600 seconds until objects get resubscribed automatically.
    CoV_list: [] #empty so it won't subscribe to anything
    quick_poll_rate: 5 #every object under quick_poll_rate will be read every 5 seconds. keyword "all" can't be used here.
    quick_poll_list: 
      - analogValue:1839
      - analogValue:1940 #any other objects you want to be polled quickly.
    slow_poll_rate: 600
    slow_poll_list:
      - all #every object will be read every 600 seconds.
  - deviceID: device:77001
    CoV_lifetime: 600
    CoV_list: 
      - all
    quick_poll_rate: 5 
    quick_poll_list: []
    slow_poll_rate: 600
    slow_poll_list:
      - all
  - deviceID: device:77000
    CoV_lifetime: 600
    CoV_list: 
      - all
    quick_poll_rate: 5 
    quick_poll_list: []
    slow_poll_rate: 600
    slow_poll_list:
      - all
  - deviceID: all #any remaining devices not mentioned will use these settings.
    CoV_lifetime: 600
    CoV_list: 
      - all
    quick_poll_rate: 5 
    quick_poll_list: []
    slow_poll_rate: 600
    slow_poll_list:
      - all
```

You could use quick polling for any object you want to be updated quickly, so might be worth a try.
